### ISSUE TITLE
Generate a tabular report

### ISSUE THREAD

**Issue by rjchallis** [genomehubs/genomehubs#120]
Generate a report of counts by group by re-using the term/ histogram aggregations from the histogram and scatter reports.

Table presentation will show the numbers directly for reporting and number of bins need not be constrained by plotting considerations

**Comment by Euphrasiologist** [comment]
This would be useful for goat-cli too!

**Comment by rjchallis** [comment]
Tabular report exists, but needs some improvements (see #222)
