### ISSUE TITLE
Add toggle switches to hide/display reports on GoaT-ui

### ISSUE THREAD

**Issue by ccaio** [genomehubs/genomehubs#129]
Add switches on project pages that allow people to opt in or out of displaying specific plots: 
- could make a toggle component accessible from markdown to allow grid rows to be switched on or off

**Comment by rjchallis** [comment]
Have added options to the grid component to allow toggling:
- `toggle` (required) creates a toggleable box around a grid row (use `toggle=false` to create the box but not show the toggle, only makes sense with `expand)
- `expand` sets the contents to be visible when the page is first opened, omit this to leave it up to the user to expand the box
- `title` sets a title for the box

e.g.:
```
:::grid{container toggle expand title="Some plots" direction="row" spacing="1"}

::report{report="xInY" x="assembly_span" rank="phylum,class,order,family,genus,species" includeEstimates excludeAncestral="assembly_span" excludeMissing="assembly_span" caption="Taxa with assemblies out of all INSDC Eukaryotic taxa" item xs=6}

::report{report="xPerRank" caption="Counts of all taxa with information on GoaT" item xs=6 }

:::
```

and a screenshot with more rows:
<img width="924" alt="image" src="https://user-images.githubusercontent.com/6704492/166716920-94c9762d-680a-4193-9e2d-8a6390825b85.png">
