### ISSUE TITLE
Fix label display/ fitting for histograms

### ISSUE THREAD

**Issue by ccaio** [genomehubs/genomehubs#178]
Large text of labels currently overlap instead of creating new line (assembly index reports):

[Histo example](https://goat.genomehubs.org/report?report=scatter&x=contig_n50%20AND%20bioproject_accession%3DPRJNA489243&y=scaffold_n50&cat=assembly_type&result=assembly&xOpts=10000%2C1000000000%2C11%2Clog10&yOpts=10000%2C1000000000%2C11%2Clog10&scatterThreshold=10000&highlightArea=1000000%2C10000000%2C1000000000%2C1000000000%2CEBP%20metric%20zone&caption=Contiguity%20assessment%20of%20VGP%20assemblies.%20EBP%20metric%20zone%20defines%20the%20EBP%20assembly%20quality%20standards%20of%20a%20contig%20N50%20%3E%201Mb%20and%20a%20scaffold%20N50%20%3E%2010Mb&taxonomy=ncbi&includeEstimates=false)

**Comment by rjchallis** [comment]
When this happens, would you prefer the labels to be made taller to accommodate multiple lines, wider to avoid needing to wrap the text, truncated to fit the available height/width with a tool tip to show the full caption, some combination of these options or something else entirely?

**Comment by ccaio** [comment]
Possibility to change labels is good regardless of the solution. I think making them wider is better than taller because some labels are essentially long single words (e.g. alternate-pseudohaplotype) that users might need to print/screenshot.
