### ISSUE TITLE
rename xInY plots

### ISSUE THREAD

**Issue by rjchallis** [genomehubs/genomehubs#196]
The xInY report title is not very user friendly so it would be good to rename to something that conveys the plot rainbow and donut plot shapes that it is used to generate. Will be important to ensure that the existing name is mapped to the new plot name to ensure old URLs remain valid.

Thanks to @Euphrasiologist for suggesting `arc`.

**Comment by ccaio** [comment]
Just throwing more options around: `hoop`, `radial`

**Comment by rjchallis** [comment]
renamed to arc
