### ISSUE TITLE
make tax_rank(species) a default term in assembly index queries

### ISSUE THREAD

**Issue by ccaio** [genomehubs/genomehubs#199]
As assembly index queries will always retrieve species-level lists, it would be more straightforward if tax_rank=species was a default query term for the index.

**Comment by rjchallis** [comment]
assemblies may be associated with either subspecies or species level taxon IDs so setting species as a default value would exclude a large proportion of the assemblies from the results. It may be good to remove higher ranks from the list of options in the query builder, but generally it is not necessary to set tax_rank at all so this parameter can usually just be ignored for assembly index queries.
