### ISSUE TITLE
Allow transposing of results from one index as input in queries of different index

### ISSUE THREAD

**Issue by ccaio** [genomehubs/genomehubs#200]
Users might see value in using one type of query to refine a search that can only be done in a different GoaT index. Perhaps allowing transposition between indices might help.

**Use case example:** refine query results using genome size (taxon index) to retrieve a list of taxa to be used as input in queries in the assembly index.

**Comment by rjchallis** [comment]
I've just pushed some changes to make parts of this possible. Named input queries are now supported by the API, but I'm not sure what the UI component should look like. 

The idea is that input queries can be defined as `queryA`, `queryB`, etc (need to match the pattern `query[A-Z]` and these will be executed ahead of the main query. If the queries use a different index, then that needs to pe specified using an `indexName--` prefix. The main query can then refer back to these input queries, e.g. to search for assemblies for any canid species on the DToL long list that has a scaffold N50 greater than that of the primary wolf assembly:

```
queryA=taxon--tax_tree(Canidae) AND tax_rank(species) AND long_list=DTOL
queryB=taxon--tax_name(Canis lupus)
query=tax_tree(queryA.taxon_id) AND scaffold_n50 >= queryB.taxon_id&result=assembly
```

There are still some arbitrary limits, e.g. the number of results the input queries can return is capped at 500, but I'll include this in the next release to make it available for experimentation.
