### ISSUE TITLE
Suggestion to separate direct and descendent values from ancestral estimates

### ISSUE THREAD

**Issue by ccaio** [genomehubs/genomehubs#214]
Mark suggested that it would be useful to do a list that had (a) direct and descendant estimates and (b) inferred from ancestor estimates, as (a) are more credible than (b).

Is that possible in one query in GoaT (ie have a column represented twice in the output, with different filters)?

Alternatively, would it be possible to generate a column displaying the aggregation source next to the attribute values?

**Comment by rjchallis** [comment]
This is now possible (release 2.6.9) by using column settings icon to set summary values/sources to display for each attribute
