### ISSUE TITLE
unable to sort results or build queries using organelle attribute

### ISSUE THREAD

**Issue by ccaio** [genomehubs/genomehubs#249]
Assembly index queries using the organelle attribute values do not return results (invalid value for organelle in organelle=nucleus). 

Sorting a valid query result using the organelle field returns a 0 hits page: "Could not load search/ search_phase_execution_exception".

**Comment by rjchallis** [comment]
I've set `type: keyword` for organelle in the assembly yaml template which should fix the sorting. Will need to try a full import to check if this is also the cause of the `invalid value` error

**Comment by rjchallis** [comment]
Searches with `organelle = nucleus` are working in the latest import
