### ISSUE TITLE
Inconsistent behaviour of pop-ups

### ISSUE THREAD

**Issue by ccaio** [genomehubs/genomehubs#264]
From a search [like this](https://goat.genomehubs.org/search?query=tax_tree%28phyllostomidae%29%20AND%20tax_rank%28species%29&result=taxon&includeEstimates=true&summaryValues=count&taxonomy=ncbi&size=100#tax_tree(phyllostomidae)%20AND%20tax_rank(species)), clicking on values will generate a pop-up with the row of records for that attribute.

After using the icon to show/hide subset columns, the [pop up](https://goat.genomehubs.org/search?query=tax_tree%28phyllostomidae%29%20AND%20tax_rank%28species%29&result=taxon&includeEstimates=true&summaryValues=count&taxonomy=ncbi&size=100&offset=0&fields=haploid_number%2Chaploid_number%3Adirect%2Chaploid_number%3Aancestor%2Chaploid_number%3Adescendant#tax_tree(phyllostomidae)%20AND%20tax_rank(species)) changes to the box where subset values can be selected.

After subsets have been selected once, there is no consistency of which pop-up box will appear. For example, the subset selection pop-up will sometimes appear when I do the following steps:
1. query only tax_tree,  
2. select haploid_number subset 
3. go back on the page to original search, 
4. click to see the records for a genome size entry (see pic)
<img width="1257" alt="Screenshot 2023-04-04 at 16 01 05" src="https://user-images.githubusercontent.com/13206220/229842485-47d4724f-2269-4f82-9f29-de93b1278be1.png">

Going back to previous search does not solve the problem, but copying the original search link and opening on a new tab seems to solve it.

**Comment by rjchallis** [comment]
fixed in latest release
