### ISSUE TITLE
Histograms with dates not expanding

### ISSUE THREAD

**Issue by ccaio** [genomehubs/genomehubs#271]
Histograms based on min(assembly_date) or max(assembly_date) do not expand to search - [example 1](https://goat.genomehubs.org/projects/EBP);Those that don't need min(assembly_date) are expanding fine - [example 2](https://goat.genomehubs.org/report?report=histogram&x=assembly_date&rank=species&cat=assembly_level&stacked=true&includeEstimates=true&excludeAncestral%5B0%5D=assembly_span&excludeMissing%5B0%5D=assembly_span&caption=Progress%20of%20genome%20assemblies%20published%20on%20INSDC%20over%20time%2C%20by%20assembly%20level&taxonomy=ncbi&result=taxon).

**Comment by rjchallis** [comment]
@ccaio - There are a lot of plots in the example 1 link - can you point me to a single plot so I can take a look

**Comment by rjchallis** [comment]
I think I see what is happening here at last. Taking [this example](https://goat.genomehubs.org/report?report=histogram&x=max%28assembly_date%29%20AND%20bioproject%3DPRJNA533106&result=taxon&cat=assembly_level%3Dcontig%2Cscaffold%2Cchromosome%2Ccomplete%20genome&stacked=true&cumulative=true&includeEstimates=true&rank=Family&xOpts=2006%2C2023%2C2%2C%2CAssembly%20date&caption=Cumulative%20number%20of%20eukaryotic%20families%20for%20which%20assemblies%20were%20generated%20by%20EBP%20affiliates%20over%20time&taxonomy=ncbi), the expanded plots picks up `assembly_level` as the x axis term as the `max()` prevents the parser seeing the `assembly_date` attribute
