### ISSUE TITLE
Allow cat: "sequencing_status_{{project}}"

### ISSUE THREAD

**Issue by ccaio** [genomehubs/genomehubs#296]
I am trying to create histogram templates for sequencing status reports (see DToL project page for [working example](https://goat.genomehubs.org/report?report=histogram&x=long_list%3DDTOL%20AND%20sequencing_status_dtol&rank=species&result=taxon&cat=sequencing_status_dtol%3Dsample_collected%2Csample_acquired%2Cin_progress%2Cinsdc_open&excludeAncestral%5B0%5D=long_list&excludeMissing%5B0%5D=long_list&xOpts=%2C%2C1%2C%2CSequencing%20Status&caption=Current%20sequencing%20status%20of%20DToL%20targets&taxonomy=ncbi)).

It looks like `cat` cannot recognise `{{project}}` placeholder inside `sequencing_status_{{project}}`.

While histo with cat above can't load, the code below returns a histo, but not with the correct counts for the projects:

```report
report: histogram
x: "long_list={{project}} AND sequencing_status_{{project}}"
y: "sequencing_status_{{project}}"
rank: species
cat: "sequencing_status=sample_collected,sample_acquired,in_progress,open,insdc_open"
includeEstimates: false
excludeAncestral: sequencing_status_{{project}}
excludeMissing: sequencing_status_{{project}}
xOpts: ",,1,,Sequencing Status"
caption: "Current status of {{project}} target species"
item: true
xs: 4
```

**Comment by rjchallis** [comment]
How about
```
report: histogram
x: "long_list={{project}} AND sequencing_status_{{lc_project}}"
y: "sequencing_status_{{lc_project}}"
rank: species
cat: "sequencing_status=sample_collected,sample_acquired,in_progress,open,insdc_open"
includeEstimates: false
excludeAncestral: sequencing_status_{{lc_project}}
excludeMissing: sequencing_status_{{lc_project}}
xOpts: ",,1,,Sequencing Status"
caption: "Current status of {{project}} target species"
item: true
xs: 4
```

All attribute names need to be lower case so you can use the `lc_` prefix inside the curly braces to convert `project` to lowercase whenever you use it as part of an attribute name.

**Comment by ccaio** [comment]
All working, Thanks!

Sorry, I hadn't realised that was already possible.  Will add to docs :)
