### ISSUE TITLE
Newick error

### ISSUE THREAD

**Issue by Euphrasiologist** [genomehubs/genomehubs#310]
Can't work out what's wrong with this query:

https://goat.genomehubs.org/api/v2/report?result=taxon&report=tree&x=tax_rank%28genus%29%20AND%20tax_tree%28Orobanchaceae%29&includeEstimates=true&taxonomy=ncbi&queryId=goat_cli_U2vILcHe4peH3XQ

It comes back with a 'number_format_exception'? But I don't know what that refers too.

**Comment by rjchallis** [comment]
This query works with `&treeThreshold=100`. The default should be 2000 and setting a threshold lower than the number of leaves (91) gives a different error so I'll have to debug that, but for now including treeThreshold should be enough to get it working
