### ISSUE TITLE
Saved queries go to blank page

### ISSUE THREAD

**Issue by PAMorin** [genomehubs/genomehubs#318]
Hi, I have a number of bookmarked queries, but when I try to open them, I see the query box briefly and then a blank browser window. These have worked in the past, and I can still get to the standard GoaT pages through the main page and links (https://goat.genomehubs.org/). I've tried the saved query links in two browsers (Safari and Chrome), and two computers (Macbook Pro and Windows), with the same results. 

Some of the saved queries:
https://goat.genomehubs.org/search?query=assembly_span%20AND%20tax_tree%289721%29%20AND%20tax_rank%28species%29&result=taxon&includeEstimates=false&fields=assembly_level%2Cscaffold_n50%2Cebp_metric_date%2Cbioproject%2Csequencing_status&summaryValues=count&taxonomy=ncbi&report=tree&offset=0&names=common_name&ranks=&y=scaffold_n50&rank=species&plotRatio=auto&pointSize=10&size=100&xField=assembly_span&treeStyle=rect&treeThreshold=2000#assembly_span%20AND%20tax_tree(9721)%20AND%20tax_rank(species)

https://goat.genomehubs.org/search?query=tax_tree%289721%29%20AND%20tax_rank%28species%29%20AND%20scaffold_n50%3E%3D100000000%20AND%20assembly_level%20AND%20sequencing_status%20AND%20ebp_standard_date%3E%3D2019-01-01&result=taxon&includeEstimates=false&summaryValues=count&taxonomy=ncbi&offset=0&fields=ebp_standard_date%2Cassembly_level%2Cscaffold_n50%2Cbusco_completeness%2Cchromosome_number%2Csequencing_status&names=common_name&ranks=&size=25&sortBy=scientific_name&sortOrder=asc#tax_tree(9721)%20AND%20tax_rank(species)%20AND%20scaffold_n50%3E%3D100000000%20AND%20assembly_level%20AND%20sequencing_status%20AND%20ebp_standard_date%3E%3D2019-01-01

https://goat.genomehubs.org/search?result=taxon&includeEstimates=false&fields=assembly_level%2Cscaffold_n50%2Cebp_metric_date%2Cbioproject%2Csequencing_status&summaryValues=count&taxonomy=ncbi&report=tree&offset=0&names=common_name&ranks=&y=scaffold_n50&rank=species&plotRatio=auto&pointSize=15&sortBy=scientific_name&query=tax_tree%289721%29%20AND%20tax_rank%28species%29%20AND%20scaffold_n50%20AND%20assembly_level%3D%3Dchromosome%20AND%20sequencing_status&size=25&sortOrder=asc#tax_tree(9721)%20AND%20tax_rank(species)%20AND%20scaffold_n50%20AND%20assembly_level%3D%3Dchromosome%20AND%20sequencing_status

https://goat.genomehubs.org/search?query=assembly_span%20AND%20tax_tree%289721%29%20AND%20tax_rank%28species%29&result=taxon&includeEstimates=false&fields=mitochondrion_assembly_span%2Cscaffold_n50%2Ccontig_n50%2Cebp_metric_date%2Clong_list%2Csequencing_status_canbp%2Csequencing_status_cgp%2Csequencing_status_dtol%2Csequencing_status_vgp&summaryValues=count&taxonomy=ncbi&report=tree&offset=0&names=common_name&ranks=&y=scaffold_n50&rank=species&plotRatio=auto&pointSize=10&size=100&xField=assembly_span&treeStyle=rect&treeThreshold=2000&sortBy=scientific_name&sortOrder=asc#assembly_span%20AND%20tax_tree(9721)%20AND%20tax_rank(species)

**Comment by rjchallis** [comment]
Thanks for letting us know - I fixed a bug in the display code and these are all working again now
