### ISSUE TITLE
No files visible at download.mealybug.org

### ISSUE THREAD

**Issue by mojcaNIB** [genomehubs/genomehubs#42]
Hi,
I am trying to download some files from the MealyBugBase but I cannot see any. Are they only currently not available?

Thanks for help.

**Comment by sujaikumar** [comment]
Hi. I'm able to see files for downloading at https://download.mealybug.org/v1/ using Safari on MacOS.

**Comment by mojcaNIB** [comment]
I am on Windows and I tried with Chrome and Firefox, but cannot see any files listed. On whatever folder I click, nothing appears in the right window. I tried accessing files on download. of different communities, e.g on caenorhabditis and I can see files listed there, only for the mealybugs I don't see anything.

**Comment by sujaikumar** [comment]
You're right - I didn't actually click through till a subfolder - I can't
see any files either. I'll look into this. Thanks for pointing it out!

**Comment by sujaikumar** [comment]
Should be fixed now. It was a file permissions issue. Thanks again for pointing it out! :-)

**Comment by mojcaNIB** [comment]
No problem, thank you for quick response and fix!

**Comment by sasamori0619** [comment]
Hi. Now I cannot access to files on download.mealybug.org. Is this problem due to my environment?
The symptoms are the same as above. I am on Windows and tried with Chrome, Firefox and Microsoft Edge. I can access files on download. of different communities.

Thanks for help.
