### ISSUE TITLE
Check all names / synonyms while indexing new data in GoaT

### ISSUE THREAD

**Issue by sujaikumar** [genomehubs/genomehubs#47]
Currently, if there is a taxon_id provided, then new metadata being indexed using `genomehubs index` is hung on the node with that taxon_id. If there is no taxon_id (which is usually the case, eg for legislation, species target lists etc) then the species name in the data to be indexed is only checked against the scientific name of taxa in GoaT. Ideally we should check ALL names/synonyms for each taxon.

If there are two taxa in GoaT that match the same name (usually the case with subspecies, eg "genus species subspecies" and "genus subspecies" both exist, or else the same "genus species" names are in two totally different phyla), the ambiguity could be resolved by checking lineages from most specific specific to least. For each lineage provided in the new data file being indexed, all lineage synonyms should be checked too.

If still ambiguous, then the new data should be reported in the exceptions folder.

**Comment by rjchallis** [comment]
synonyms can be checked with `--taxon-lookup any` and this implementation was improved as part of #58. 

This should be checking lineage synonyms but I haven't tested that aspect.
