### ISSUE TITLE
add comment character(s) to names/types.yaml to ignore when indexing

### ISSUE THREAD

**Issue by sujaikumar** [genomehubs/genomehubs#54]
Defaults can be "#", and "//", with perhaps the possibility of adding new ones in yaml?

**Comment by rjchallis** [comment]
Works on single character at start of string for ease/efficiency. Default is `#` and others can be added in yaml, e.g.:

```
file:
  format: tsv
  comment: ;
...
```

multiple alternative characters can be specified as an array:
```
file:
  format: tsv
  comment:
    - /
    - ;
...
```
