### ISSUE TITLE
Set default traverse limit to class in genomehubs fill command line

### ISSUE THREAD

**Issue by sujaikumar** [genomehubs/genomehubs#64]

**Comment by rjchallis** [comment]
Default value (class) can be changed using `--traverse-limit` or overridden on a per-attribute basis by setting `traverse_limit` in the import config yaml file
```
genomehubs fill --traverse-limit phylum ...
```

Useful to make sure at least one `display_level: 1` attribute has a limit set to the root of the tree (or higher) to allow search results for higher taxa and taxa in groups with no direct values to be shown.
